"use client";
import { ChangeEvent, FormEvent, useMemo, useState } from "react";
import { getAdultBirthDateLimit, getFullAge } from "../../lib/profile-utils";
import { PhotoReview, Profile } from "../../types/profile";

export function BasicProfileForm({ profile, review, onProfile, onReview, onComplete }: { profile:Profile; review:PhotoReview; onProfile:(p:Profile)=>void; onReview:(r:PhotoReview)=>void; onComplete:()=>void }) {
  const [error,setError]=useState(""); const adultLimit=useMemo(()=>getAdultBirthDateLimit(),[]);
  function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(file.size>3*1024*1024){setError("사진은 3MB 이하로 선택해 주세요.");onReview("rejected");return}onReview("reviewing");setError("");const reader=new FileReader();reader.onload=()=>{onProfile({...profile,photo:String(reader.result)});setTimeout(()=>onReview("approved"),1200)};reader.readAsDataURL(file)}
  function submit(e:FormEvent){e.preventDefault();if(!profile.photo||review!=="approved"){setError("승인된 정면 얼굴 사진이 필요해요.");return}if(!profile.name||!profile.birthDate||!profile.gender||!profile.region||!profile.intro){setError("필수 항목을 모두 채워 주세요.");return}if(getFullAge(profile.birthDate)<18){setError("만 18세 이상만 이용할 수 있어요.");return}setError("");onComplete()}
  return <div className="auth-card profile-form"><div className="step-label">03 · 기본 프로필</div><h2>먼저 기본부터 알려주세요</h2><p className="subcopy">사진과 기본 정보 다음에 재미있는 성향 태그를 골라요.</p><form onSubmit={submit}><div className="photo-row"><label className="photo-upload required">{profile.photo?<img src={profile.photo} alt="프로필 미리보기"/>:<span>＋<small>사진 필수</small></span>}<input type="file" required={!profile.photo} accept="image/png,image/jpeg,image/webp" onChange={upload}/></label><div className="photo-guide"><b>정면 얼굴 사진 *</b><small>본인 얼굴이 선명한 사진만 등록할 수 있어요.</small>{review==="reviewing"&&<em className="review reviewing">◌ 사진 심사 중...</em>}{review==="approved"&&<em className="review approved">✓ 정면 얼굴 사진 승인</em>}</div></div><div className="two-col"><label>닉네임 *<input value={profile.name} onChange={e=>onProfile({...profile,name:e.target.value})}/></label><label>생년월일 *<input type="date" max={adultLimit} value={profile.birthDate} onChange={e=>onProfile({...profile,birthDate:e.target.value})}/></label></div><fieldset className="gender-field"><legend>성별 *</legend><div className="gender-pick"><button type="button" className={profile.gender==="male"?"active":""} onClick={()=>onProfile({...profile,gender:"male"})}>남성</button><button type="button" className={profile.gender==="female"?"active":""} onClick={()=>onProfile({...profile,gender:"female"})}>여성</button></div></fieldset><label>활동 지역 *<select value={profile.region} onChange={e=>onProfile({...profile,region:e.target.value})}><option value="">선택해 주세요</option>{["서울","경기","인천","부산","대전","대구","광주","제주"].map(x=><option key={x}>{x}</option>)}</select></label><label>하는 일<input value={profile.job} onChange={e=>onProfile({...profile,job:e.target.value})}/></label><label>한 줄 소개 *<textarea maxLength={120} value={profile.intro} onChange={e=>onProfile({...profile,intro:e.target.value})}/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={review!=="approved"}>성향 고르러 가기<span>→</span></button></form></div>;
}
