"use client";
import { useState } from "react";
import { DEMO_PROFILES } from "../../data/demo-profiles";
import { PublicProfile } from "../../types/profile";

export type RequestItem={id:string;profile:PublicProfile;message:string};
export type ActiveChat={id:string;profile:PublicProfile;lastMessage:string};

export function ChatHub({sent,setSent,active,setActive,received,setReceived}:{sent:RequestItem[];setSent:(x:RequestItem[])=>void;active:ActiveChat[];setActive:(x:ActiveChat[])=>void;received:RequestItem[];setReceived:(x:RequestItem[])=>void}){
 const [tab,setTab]=useState<"active"|"received"|"sent">("active");const [shop,setShop]=useState(false);const [limit,setLimit]=useState(false);const [leaving,setLeaving]=useState<ActiveChat|null>(null);const total=2;
 function accept(item:RequestItem,source:"sent"|"received"){if(active.length>=total){setLimit(true);return}setActive([...active,{id:`chat-${item.id}`,profile:item.profile,lastMessage:"대화를 시작해보세요."}]);if(source==="sent")setSent(sent.filter(x=>x.id!==item.id));else setReceived(received.filter(x=>x.id!==item.id));setTab("active")}
 return <div className="mobile-screen chat-hub"><header className="app-header"><div><b>대화</b><span>활성 대화 {active.length} / {total}</span></div><button onClick={()=>setShop(true)} aria-label="대화 공간 상점">＋</button></header><nav className="chat-tabs"><button className={tab==="active"?"active":""} onClick={()=>setTab("active")}>진행 중</button><button className={tab==="received"?"active":""} onClick={()=>setTab("received")}>받은 요청</button><button className={tab==="sent"?"active":""} onClick={()=>setTab("sent")}>보낸 요청</button></nav>{tab==="active"&&<div className="chat-list">{active.length?active.map(chat=><article key={chat.id}><img src={chat.profile.photo} alt=""/><div><b>{chat.profile.name}</b><p>{chat.lastMessage}</p></div><button onClick={()=>setLeaving(chat)} aria-label="대화 나가기">↗</button></article>):<Empty text="아직 진행 중인 대화가 없어요."/>}</div>}{tab==="received"&&<div className="request-list">{received.map(item=><RequestRow key={item.id} item={item} action="대화 시작하기" onAction={()=>accept(item,"received")}/>)}{!received.length&&<Empty text="받은 요청이 없어요."/>}</div>}{tab==="sent"&&<div className="request-list">{sent.map(item=><RequestRow key={item.id} item={item} action="Mock 수락" onAction={()=>accept(item,"sent")}/>)}{!sent.length&&<Empty text="보낸 요청이 없어요."/>}</div>}{shop&&<Modal onClose={()=>setShop(false)} title="대화 공간 늘리기"><p>동시에 이야기할 수 있는 대화 공간을 늘릴 수 있어요.</p><div className="slot-product"><b>대화 공간 +1</b><span>가격 준비 중</span></div></Modal>}{limit&&<Modal onClose={()=>setLimit(false)} title="대화 공간이 모두 사용 중이에요"><p>현재 두 사람과 대화하고 있습니다. 기존 대화를 마무리하거나 대화 공간을 하나 더 늘려주세요.</p><button className="modal-main" onClick={()=>{setLimit(false);setShop(true)}}>대화 공간 늘리기</button></Modal>}{leaving&&<Modal onClose={()=>setLeaving(null)} title="이 대화를 나갈까요?"><p>대화를 나가면 이 채팅은 종료되고 사용 중인 대화 공간 1개가 비워집니다.</p><button className="modal-danger" onClick={()=>{setActive(active.filter(x=>x.id!==leaving.id));setLeaving(null)}}>대화 나가기</button></Modal>}</div>
}
function RequestRow({item,action,onAction}:{item:RequestItem;action:string;onAction:()=>void}){return <article><img src={item.profile.photo} alt=""/><div><b>{item.profile.name}</b><p>{item.message}</p><small>요청 상태는 슬롯을 사용하지 않아요.</small></div><button onClick={onAction}>{action}</button></article>}
function Empty({text}:{text:string}){return <div className="empty-state"><span>💬</span><p>{text}</p></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="app-modal" role="button" tabIndex={0} aria-label="팝업 닫기" onClick={onClose} onKeyDown={e=>{if(e.key==="Escape"||e.key==="Enter")onClose()}}><section role="presentation" onClick={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><h2>{title}</h2>{children}</section></div>}

export function initialReceived(gender:ProfileGender):RequestItem[]{const candidates=DEMO_PROFILES.filter(p=>p.gender!==gender).slice(1,4);return candidates.map((p,i)=>({id:`received-${i}`,profile:p,message:["프로필의 여행 이야기가 궁금해요.","좋아하는 음악 얘기 나눠보고 싶어요.","같이 맛집 이야기해요!"][i]}))}
type ProfileGender="male"|"female"|"";
